#!/bin/bash
cd `dirname $0`
source armbian-sysinfo

case $1 in
        get_throttled) echo "throttled=0x0";;
        measure_temp) echo "temp=$board_temp'C";;
        get_config)
                case $2 in
                        total_mem)
                                NUM=$( free -m | grep Mem: | awk '{print $2}' )
                                KB=$( sudo grep 'Memory:' /var/log/dmesg | awk '{print $5}' | cut -d'/' -f2 | sed 's/K//g' | head -1 )
                                if [[ "$KB" == "" ]]; then
                                        GB=`echo "( $NUM + 256 ) / 256" | bc`
                                        MB=$( echo "${GB} * 256" | bc )
                                else
                                        MB=$( echo $KB / 1024 | bc )
                                fi
                                echo "total_mem=$MB"
                                ;;
                        *)
                                echo "invalid option";;
                esac
        ;;
esac
