#!/bin/sh
/etc/update-motd.d/10-armbian-header
/etc/update-motd.d/30-armbian-sysinfo
/etc/update-motd.d/41-armbian-config

printf "    Welcome to Armbian-KVM - Open Source IP-KVM installed on Orange Pi
    ____________________________________________________________________________

    To prevent kernel messages from printing to the terminal use \"dmesg -n 1\".

    To change KVM password use command \"kvmd-htpasswd set admin\".

    Useful links:
      * https://pikvm.org
      * https://docs.pikvm.org
      * https://github.com/srepac/kvmd-armbian
      * https://wiki.archlinux.org/title/systemd-networkd

"

cat /etc/motd.custom
