#!/bin/sh
if [ -e /etc/update-motd.d/10-armbian-header ]; then /etc/update-motd.d/10-armbian-header; fi
if [ -e /etc/update-motd.d/30-armbian-sysinfo ]; then /etc/update-motd.d/30-armbian-sysinfo; fi
if [ -e /etc/update-motd.d/41-armbian-config ]; then /etc/update-motd.d/41-armbian-config; fi

printf "    Welcome to Armbian-KVM - Open Source IP-KVM installed
    ____________________________________________________________________________

    To prevent kernel messages from printing to the terminal use \"dmesg -n 1\".

    To change KVM password use command \"kvmd-htpasswd set admin\".

    Useful links:
      * https://pikvm.org
      * https://docs.pikvm.org
      * https://github.com/srepac/kvmd-armbian
      * https://wiki.archlinux.org/title/systemd-networkd

"

if [ -e /etc/motd.custom ]; then cat /etc/motd.custom; fi
