#!/bin/sh
if [ -e /etc/update-motd.d/10-armbian-header ]; then /etc/update-motd.d/10-armbian-header; fi
if [ -e /etc/update-motd.d/30-armbian-sysinfo ]; then /etc/update-motd.d/30-armbian-sysinfo; fi
if [ -e /etc/update-motd.d/41-armbian-config ]; then /etc/update-motd.d/41-armbian-config; fi

printf "    Welcome to PiKVM - Open Source IP-KVM installed on SBC
    ____________________________________________________________________________

    Useful commands:
      * Preventing kernel messages in the console:  dmesg -n 1
      * Changing the Web UI password:  kvmd-htpasswd set admin
      * Changing the root password:    passwd

    Links:
      * Official website:  https://pikvm.org
      * Documentation:     https://docs.pikvm.org
      * Auth & 2FA:        https://docs.pikvm.org/auth
      * Networking:        https://wiki.archlinux.org/title/systemd-networkd
      * https://github.com/srepac/kvmd-armbian

"

if [ -e /etc/motd.custom ]; then cat /etc/motd.custom; fi
